// <auto-generated />
namespace EmployeeApi.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.5.1")]
    public sealed partial class editSalaryTable : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(editSalaryTable));
        
        string IMigrationMetadata.Id
        {
            get { return "202511030625119_editSalaryTable"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
